version: '2'
services:
    esempioangular-app:
        image: esempioangular
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://esempioangular-mysql:3306/esempioangular?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    esempioangular-mysql:
        extends:
            file: mysql.yml
            service: esempioangular-mysql
